wandb_version: 1

layer_1:
  desc: null
  value: 6
activation_1:
  desc: null
  value: tanh
layer_2:
  desc: null
  value: 6
activation_2:
  desc: null
  value: tanh
layer_3:
  desc: null
  value: 6
activation_3:
  desc: null
  value: tanh
optimizer:
  desc: null
  value: adam
layer_4:
  desc: null
  value: 6
activation_4:
  desc: null
  value: softmax
loss:
  desc: null
  value: sparse_categorical_crossentropy
metric:
  desc: null
  value: accuracy
epoch:
  desc: null
  value: 30
batch_size:
  desc: null
  value: 16
_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.15.8
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1691719134.633588
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.10.6
      5: 0.15.8
      8:
      - 3
      - 5
